dist:
  trusty

sudo:
  false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-unstable

language:
  node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "lts/*"

git:
  depth:
    3

cache:
  directories:
    - node_modules

notifications:
  email:
    false

script:
  - npm run travis
